var mapping = {
  "/": "/plus/overview/",
  "/docs/usage/introduction/": "/plus/overview/",
  "/docs/usage/setup/": "/plus/quick-start/",
  "/docs/usage/security/": "",
  "/docs/usage/install-pmx/": "/plus/reference/pmx/",
  "/docs/usage/pmx-keymetrics-library/": "/plus/reference/pmx/",
  "/docs/pages/faq-troubleshooting/": "",
  "/docs/pages/pricing-faq": "/pricing",
  "/docs/pages/dashboard/": "",
  "/docs/pages/monitoring/": "",
  "/docs/pages/issues/": "/plus/guide/issue-dashboard/",
  "/docs/pages/tracing/": "/plus/guide/transaction-tracing/",
  "/docs/pages/alert-system/": "/plus/guide/notifications/",
  "/docs/pages/custom-metrics/": "/plus/guide/configuration/",
  "/docs/pages/custom-actions/": "/plus/guide/configuration/",
  "/docs/pages/events/": "/plus/guide/configuration/",
  "/docs/pages/profiling/": "/plus/guide/memory-cpu-profiling/",
  "/docs/pages/integrations/": "/plus/guide/notifications/",
  "/docs/usage/paas-heroku-azure/": "/plus/integration/cloud-providers/",
  "/docs/usage/keymetrics-changelog/": "",
  "/docs/usage/from-trace-to-keymetrics/": "",
  "/docs/pages/versioning-management/": "",
  "/docs/pages/http/": "/plus/guide/transaction-tracing/",
}

var newUrl = "pm2.io/doc/en" + mapping[document.location.pathname];